name: Update Job Listings

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run job scraper
        run: |
          python scripts/job_scraper.py
          
      - name: Run job filter
        run: |
          python scripts/job_filter.py
          
      - name: Update last updated timestamp
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S')" > last_updated.txt
          
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add filtered_jobs.json government_it_jobs.json last_updated.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update job listings: $(date +'%Y-%m-%d')" && git push)
